sso-operator:
  dex:
    grpcHost: "dex.jx"
dex:
  domain: "dex-jx.{{ .Requirements.ingress.domain }}"
  connectors:
    github:
      config:
        clientID: "{{ .Parameters.dashboardAuthID }}"
        clientSecret: "{{ .Parameters.dashboardAuthSecret }}"
        orgs:
        - "{{ .Parameters.dashboardAuthOrg }}"
