adminUser:
  password: vault:jx-aps-consumer-gjq/adminUser:password
  username: admin
dashboardAuthID: vault:jx-aps-consumer-gjq:dashboardAuthID
dashboardAuthOrg: arcalos-dashboard
dashboardAuthSecret: vault:jx-aps-consumer-gjq:dashboardAuthSecret
dashboardGrpchost: dex.jx
enableDocker: false
pipelineUser:
  email: PIPELINE_GITHUB_EMAIL
  token: vault:jx-aps-consumer-gjq/pipelineUser:token
  username: garethjevans-bot
prow:
  hmacToken: vault:jx-aps-consumer-gjq/prow:hmacToken
